[package]
name = "mcping"
version = "0.1.0"
authors = ["Scetch <lucierbrandon@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
failure = "0.1.1"
failure_derive = "0.1.1"
rand = "0.7.3"
serde = "1.0.104"
serde_json = "1.0.45"

[dev-dependencies]
dialoguer = "0.6"
anyhow = "1.0"
dns-lookup = "1.0"
